title: "HF dataset validation"

description: "Testing with HuggingFace dataset"

prompts:  'Act as {{act}}. {{prompt}}'

providers:
  - "openai:gpt-4o-mini"
  - "anthropic:messages:claude-sonnet-4-5-20250929"
  

tests: huggingface://datasets/fka/awesome-chatgpt-prompts?split=train&limit=50

