title: "Benchmarking own data"

description: "Comapre GPT modelson reasoning , cost, latency."

prompts:  "Solve this riddle: {{riddle}}"

providers:
  - "openai:gpt-4o-mini"
  - "openai:gpt-4.1"
  - "openai:gpt-4.1-mini"
  - "openai:gpt-3.5-turbo"
  - "openai:gpt-5"
  

tests:
  - vars:
      riddle: |
        I am not alive but I can grow. I don't have lungs, but I need air. I don't have a mouth, but water kills me.
        What am I?
    assert:
        - type: icontains
          value: "fire"
        - type: cost
          threshold: 0.001
        - type: latency
          threshold: 5000
        - type: llm-rubric
          value: Do not be pessimistic.
  - vars:
      riddle: |
        I run but never walk, have a bed but never sleep, and have a mouth but never eat. What am I?
    assert:
        - type: icontains
          value: "river"
        - type: cost
          threshold: 0.002
        - type: latency
          threshold: 3000
        - type: llm-rubric
          value: Ensure it is a natural feature.
  - vars:
      riddle: |
        I’m heard when I’m broken and kept when I’m whole; one word can shatter me. What am I?
    assert:
        - type: icontains
          value: "silence"
        - type: cost
          threshold: 0.003
        - type: latency
          threshold: 3000
        - type: llm-rubric
          value: Emphasize the answer relates to sound.
  - vars:
      riddle: |
        I have keys but open no locks. I have space but no room. You can enter, but you can't go outside. What am I?
    assert:
        - type: icontains
          value: "keyboard"
        - type: cost
          threshold: 0.003
        - type: latency
          threshold: 3000
        - type: llm-rubric
          value: Emphasize it has keys.
  - vars:
      riddle: |
        The more of me you take, the more you leave behind. What am I?
    assert:
        - type: icontains
          value: "footsteps"
        - type: cost
          threshold: 0.002
        - type: latency
          threshold: 5000
        - type: llm-rubric
          value: Ensure the answer is concise and to the point.